<?php

namespace Database\Seeders;

use App\Models\Depto;
use App\Models\Municipio;
use Illuminate\Database\Seeder;


class DeptoMunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $deptos = [
            ['codigodepto' => 1, 'nombredepto' => 'ATLANTIDA'],
            ['codigodepto' => 2, 'nombredepto' => 'COLON'],
            ['codigodepto' => 3, 'nombredepto' => 'COMAYAGUA'],
            ['codigodepto' => 4, 'nombredepto' => 'COPAN'],
            ['codigodepto' => 5, 'nombredepto' => 'CORTES'],
            ['codigodepto' => 6, 'nombredepto' => 'CHOLUTECA'],
            ['codigodepto' => 7, 'nombredepto' => 'EL PARAISO'],
            ['codigodepto' => 8, 'nombredepto' => 'FRANCISCO MORAZAN'],
            ['codigodepto' => 9, 'nombredepto' => 'GRACIAS A DIOS'],
            ['codigodepto' => 10, 'nombredepto' => 'INTIBUCA'],
            ['codigodepto' => 11, 'nombredepto' => 'ISLAS DE LA BAHIA'],
            ['codigodepto' => 12, 'nombredepto' => 'LA PAZ'],
            ['codigodepto' => 13, 'nombredepto' => 'LEMPIRA'],
            ['codigodepto' => 14, 'nombredepto' => 'OCOTEPEQUE'],
            ['codigodepto' => 15, 'nombredepto' => 'OLANCHO'],
            ['codigodepto' => 16, 'nombredepto' => 'SANTA BARBARA'],
            ['codigodepto' => 17, 'nombredepto' => 'VALLE'],
            ['codigodepto' => 18, 'nombredepto' => 'YORO'],

        ];

        foreach ($deptos as $depto) {
            Depto::firstOrCreate($depto);
        }


        $municipios = [
            ['codigodepto' => 1, 'codigomunicipio' => 1, 'nombremunicipio' => "LA CEIBA"],
            ['codigodepto' => 1, 'codigomunicipio' => 2, 'nombremunicipio' => "EL PORVENIR"],
            ['codigodepto' => 1, 'codigomunicipio' => 3, 'nombremunicipio' => "ESPARTA"],
            ['codigodepto' => 1, 'codigomunicipio' => 4, 'nombremunicipio' => "JUTIAPA"],
            ['codigodepto' => 1, 'codigomunicipio' => 5, 'nombremunicipio' => "LA MASICA"],
            ['codigodepto' => 1, 'codigomunicipio' => 6, 'nombremunicipio' => "SAN FRANCISCO"],
            ['codigodepto' => 1, 'codigomunicipio' => 7, 'nombremunicipio' => "TELA"],
            ['codigodepto' => 1, 'codigomunicipio' => 8, 'nombremunicipio' => "ARIZONA"],
            ['codigodepto' => 2, 'codigomunicipio' => 1, 'nombremunicipio' => "TRUJILLO"],
            ['codigodepto' => 2, 'codigomunicipio' => 2, 'nombremunicipio' => "BALFATE"],
            ['codigodepto' => 2, 'codigomunicipio' => 3, 'nombremunicipio' => "IRIONA"],
            ['codigodepto' => 2, 'codigomunicipio' => 4, 'nombremunicipio' => "LIMON"],
            ['codigodepto' => 2, 'codigomunicipio' => 5, 'nombremunicipio' => "SABA"],
            ['codigodepto' => 2, 'codigomunicipio' => 6, 'nombremunicipio' => "SANTA FE"],
            ['codigodepto' => 2, 'codigomunicipio' => 7, 'nombremunicipio' => "SANTA ROSA AGUAN"],
            ['codigodepto' => 2, 'codigomunicipio' => 8, 'nombremunicipio' => "SONAGUERA"],
            ['codigodepto' => 2, 'codigomunicipio' => 9, 'nombremunicipio' => "TOCOA"],
            ['codigodepto' => 2, 'codigomunicipio' => 10, 'nombremunicipio' => "BONITO ORIENTAL"],
            ['codigodepto' => 3, 'codigomunicipio' => 1, 'nombremunicipio' => "COMAYAGUA"],
            ['codigodepto' => 3, 'codigomunicipio' => 2, 'nombremunicipio' => "AJUTERIQUE"],
            ['codigodepto' => 3, 'codigomunicipio' => 3, 'nombremunicipio' => "EL ROSARIO"],
            ['codigodepto' => 3, 'codigomunicipio' => 4, 'nombremunicipio' => "ESQUIAS"],
            ['codigodepto' => 3, 'codigomunicipio' => 5, 'nombremunicipio' => "HUMUYA"],
            ['codigodepto' => 3, 'codigomunicipio' => 6, 'nombremunicipio' => "LA LIBERTAD"],
            ['codigodepto' => 3, 'codigomunicipio' => 7, 'nombremunicipio' => "LAMANI"],
            ['codigodepto' => 3, 'codigomunicipio' => 8, 'nombremunicipio' => "LA TRINIDAD"],
            ['codigodepto' => 3, 'codigomunicipio' => 9, 'nombremunicipio' => "LEJAMANI"],
            ['codigodepto' => 3, 'codigomunicipio' => 10, 'nombremunicipio' => "MEAMBAR"],
            ['codigodepto' => 3, 'codigomunicipio' => 11, 'nombremunicipio' => "MINAS DE ORO"],
            ['codigodepto' => 3, 'codigomunicipio' => 12, 'nombremunicipio' => "OJOS DE AGUA"],
            ['codigodepto' => 3, 'codigomunicipio' => 13, 'nombremunicipio' => "SAN JERONIMO"],
            ['codigodepto' => 3, 'codigomunicipio' => 14, 'nombremunicipio' => "SAN JOSE DE COMAYAGUA"],
            ['codigodepto' => 3, 'codigomunicipio' => 15, 'nombremunicipio' => "SAN JOSE DEL POTRERO"],
            ['codigodepto' => 3, 'codigomunicipio' => 16, 'nombremunicipio' => "SAN LUIS"],
            ['codigodepto' => 3, 'codigomunicipio' => 17, 'nombremunicipio' => "SAN SEBASTIAN"],
            ['codigodepto' => 3, 'codigomunicipio' => 18, 'nombremunicipio' => "SIGUATEPEQUE"],
            ['codigodepto' => 3, 'codigomunicipio' => 19, 'nombremunicipio' => "VILLA DE SAN ANTONIO"],
            ['codigodepto' => 3, 'codigomunicipio' => 20, 'nombremunicipio' => "LAS LAJAS"],
            ['codigodepto' => 3, 'codigomunicipio' => 21, 'nombremunicipio' => "TAULABE"],
            ['codigodepto' => 4, 'codigomunicipio' => 1, 'nombremunicipio' => "SANTA ROSA DE COPAN"],
            ['codigodepto' => 4, 'codigomunicipio' => 2, 'nombremunicipio' => "CABAÑAS"],
            ['codigodepto' => 4, 'codigomunicipio' => 3, 'nombremunicipio' => "CONCEPCION"],
            ['codigodepto' => 4, 'codigomunicipio' => 4, 'nombremunicipio' => "COPAN RUINAS"],
            ['codigodepto' => 4, 'codigomunicipio' => 5, 'nombremunicipio' => "CORQUIN"],
            ['codigodepto' => 4, 'codigomunicipio' => 6, 'nombremunicipio' => "CUCUYAGUA"],
            ['codigodepto' => 4, 'codigomunicipio' => 7, 'nombremunicipio' => "DOLORES"],
            ['codigodepto' => 4, 'codigomunicipio' => 8, 'nombremunicipio' => "DULCE NOMBRE"],
            ['codigodepto' => 4, 'codigomunicipio' => 9, 'nombremunicipio' => "EL PARAISO"],
            ['codigodepto' => 4, 'codigomunicipio' => 10, 'nombremunicipio' => "FLORIDA"],
            ['codigodepto' => 4, 'codigomunicipio' => 11, 'nombremunicipio' => "LA JIGUA"],
            ['codigodepto' => 4, 'codigomunicipio' => 12, 'nombremunicipio' => "LA UNION"],
            ['codigodepto' => 4, 'codigomunicipio' => 13, 'nombremunicipio' => "NUEVA ARCADIA"],
            ['codigodepto' => 4, 'codigomunicipio' => 14, 'nombremunicipio' => "SAN AGUSTIN"],
            ['codigodepto' => 4, 'codigomunicipio' => 15, 'nombremunicipio' => "SAN ANTONIO"],
            ['codigodepto' => 4, 'codigomunicipio' => 16, 'nombremunicipio' => "SAN JERONIMO"],
            ['codigodepto' => 4, 'codigomunicipio' => 17, 'nombremunicipio' => "SAN JOSE"],
            ['codigodepto' => 4, 'codigomunicipio' => 18, 'nombremunicipio' => "SAN JUAN DE OPOA"],
            ['codigodepto' => 4, 'codigomunicipio' => 19, 'nombremunicipio' => "SAN NICOLAS"],
            ['codigodepto' => 4, 'codigomunicipio' => 20, 'nombremunicipio' => "SAN PEDRO"],
            ['codigodepto' => 4, 'codigomunicipio' => 21, 'nombremunicipio' => "SANTA RITA"],
            ['codigodepto' => 4, 'codigomunicipio' => 22, 'nombremunicipio' => "TRINIDAD"],
            ['codigodepto' => 4, 'codigomunicipio' => 23, 'nombremunicipio' => "VERACRUZ"],
            ['codigodepto' => 5, 'codigomunicipio' => 1, 'nombremunicipio' => "SAN PEDRO SULA"],
            ['codigodepto' => 5, 'codigomunicipio' => 2, 'nombremunicipio' => "CHOLOMA"],
            ['codigodepto' => 5, 'codigomunicipio' => 3, 'nombremunicipio' => "OMOA"],
            ['codigodepto' => 5, 'codigomunicipio' => 4, 'nombremunicipio' => "PIMIENTA"],
            ['codigodepto' => 5, 'codigomunicipio' => 5, 'nombremunicipio' => "POTRERILLOS"],
            ['codigodepto' => 5, 'codigomunicipio' => 6, 'nombremunicipio' => "PUERTO CORTES"],
            ['codigodepto' => 5, 'codigomunicipio' => 7, 'nombremunicipio' => "SAN ANTONIO DE CORTES"],
            ['codigodepto' => 5, 'codigomunicipio' => 8, 'nombremunicipio' => "SAN FRANCISCO DE YOJOA"],
            ['codigodepto' => 5, 'codigomunicipio' => 9, 'nombremunicipio' => "SAN MANUEL"],
            ['codigodepto' => 5, 'codigomunicipio' => 10, 'nombremunicipio' => "SANTA CRUZ DE YOJOA"],
            ['codigodepto' => 5, 'codigomunicipio' => 11, 'nombremunicipio' => "VILLANUEVA"],
            ['codigodepto' => 5, 'codigomunicipio' => 12, 'nombremunicipio' => "LA LIMA"],
            ['codigodepto' => 6, 'codigomunicipio' => 1, 'nombremunicipio' => "CHOLUTECA"],
            ['codigodepto' => 6, 'codigomunicipio' => 2, 'nombremunicipio' => "APACILAGUA"],
            ['codigodepto' => 6, 'codigomunicipio' => 3, 'nombremunicipio' => "CONCEPCION DE MARIA"],
            ['codigodepto' => 6, 'codigomunicipio' => 4, 'nombremunicipio' => "DUYURE"],
            ['codigodepto' => 6, 'codigomunicipio' => 5, 'nombremunicipio' => "EL CORPUS"],
            ['codigodepto' => 6, 'codigomunicipio' => 6, 'nombremunicipio' => "EL TRIUNFO"],
            ['codigodepto' => 6, 'codigomunicipio' => 7, 'nombremunicipio' => "MARCOVIA"],
            ['codigodepto' => 6, 'codigomunicipio' => 8, 'nombremunicipio' => "MOROLICA"],
            ['codigodepto' => 6, 'codigomunicipio' => 9, 'nombremunicipio' => "NAMASIGUE"],
            ['codigodepto' => 6, 'codigomunicipio' => 10, 'nombremunicipio' => "OROCUINA"],
            ['codigodepto' => 6, 'codigomunicipio' => 11, 'nombremunicipio' => "PESPIRE"],
            ['codigodepto' => 6, 'codigomunicipio' => 12, 'nombremunicipio' => "SAN ANTONIO DE FLORES"],
            ['codigodepto' => 6, 'codigomunicipio' => 13, 'nombremunicipio' => "SAN ISIDRO"],
            ['codigodepto' => 6, 'codigomunicipio' => 14, 'nombremunicipio' => "SAN JOSE"],
            ['codigodepto' => 6, 'codigomunicipio' => 15, 'nombremunicipio' => "SAN MARCOS DE COLON"],
            ['codigodepto' => 6, 'codigomunicipio' => 16, 'nombremunicipio' => "SANTA ANA DE YUSGUARE"],
            ['codigodepto' => 7, 'codigomunicipio' => 1, 'nombremunicipio' => "YUSCARAN"],
            ['codigodepto' => 7, 'codigomunicipio' => 2, 'nombremunicipio' => "ALAUCA"],
            ['codigodepto' => 7, 'codigomunicipio' => 3, 'nombremunicipio' => "DANLI"],
            ['codigodepto' => 7, 'codigomunicipio' => 4, 'nombremunicipio' => "EL PARAISO"],
            ['codigodepto' => 7, 'codigomunicipio' => 5, 'nombremunicipio' => "GUINOPE"],
            ['codigodepto' => 7, 'codigomunicipio' => 6, 'nombremunicipio' => "JACALEAPA"],
            ['codigodepto' => 7, 'codigomunicipio' => 7, 'nombremunicipio' => "LIURE"],
            ['codigodepto' => 7, 'codigomunicipio' => 8, 'nombremunicipio' => "MOROCELI"],
            ['codigodepto' => 7, 'codigomunicipio' => 9, 'nombremunicipio' => "OROPOLI"],
            ['codigodepto' => 7, 'codigomunicipio' => 10, 'nombremunicipio' => "POTRERILLOS"],
            ['codigodepto' => 7, 'codigomunicipio' => 11, 'nombremunicipio' => "SAN ANTONIO DE FLORES"],
            ['codigodepto' => 7, 'codigomunicipio' => 12, 'nombremunicipio' => "SAN LUCAS"],
            ['codigodepto' => 7, 'codigomunicipio' => 13, 'nombremunicipio' => "SAN MATIAS"],
            ['codigodepto' => 7, 'codigomunicipio' => 14, 'nombremunicipio' => "SOLEDAD"],
            ['codigodepto' => 7, 'codigomunicipio' => 15, 'nombremunicipio' => "TEUPASENTI"],
            ['codigodepto' => 7, 'codigomunicipio' => 16, 'nombremunicipio' => "TEXIGUAT"],
            ['codigodepto' => 7, 'codigomunicipio' => 17, 'nombremunicipio' => "VADO ANCHO"],
            ['codigodepto' => 7, 'codigomunicipio' => 18, 'nombremunicipio' => "YAUYUPE"],
            ['codigodepto' => 7, 'codigomunicipio' => 19, 'nombremunicipio' => "TROJES"],
            ['codigodepto' => 8, 'codigomunicipio' => 1, 'nombremunicipio' => "DISTRITO"],
            ['codigodepto' => 8, 'codigomunicipio' => 2, 'nombremunicipio' => "ALUBAREN"],
            ['codigodepto' => 8, 'codigomunicipio' => 3, 'nombremunicipio' => "CEDROS"],
            ['codigodepto' => 8, 'codigomunicipio' => 4, 'nombremunicipio' => "CURAREN"],
            ['codigodepto' => 8, 'codigomunicipio' => 5, 'nombremunicipio' => "EL PORVENIR"],
            ['codigodepto' => 8, 'codigomunicipio' => 6, 'nombremunicipio' => "GUAIMACA"],
            ['codigodepto' => 8, 'codigomunicipio' => 7, 'nombremunicipio' => "LA LIBERTAD"],
            ['codigodepto' => 8, 'codigomunicipio' => 8, 'nombremunicipio' => "LA VENTA"],
            ['codigodepto' => 8, 'codigomunicipio' => 9, 'nombremunicipio' => "LEPATERIQUE"],
            ['codigodepto' => 8, 'codigomunicipio' => 10, 'nombremunicipio' => "MARAITA"],
            ['codigodepto' => 8, 'codigomunicipio' => 11, 'nombremunicipio' => "MARALE"],
            ['codigodepto' => 8, 'codigomunicipio' => 12, 'nombremunicipio' => "NUEVA ARMENIA"],
            ['codigodepto' => 8, 'codigomunicipio' => 13, 'nombremunicipio' => "OJOJONA"],
            ['codigodepto' => 8, 'codigomunicipio' => 14, 'nombremunicipio' => "ORICA"],
            ['codigodepto' => 8, 'codigomunicipio' => 15, 'nombremunicipio' => "REITOCA"],
            ['codigodepto' => 8, 'codigomunicipio' => 16, 'nombremunicipio' => "SABANAGRANDE"],
            ['codigodepto' => 8, 'codigomunicipio' => 17, 'nombremunicipio' => "SAN ANTONIO DE ORIENTE"],
            ['codigodepto' => 8, 'codigomunicipio' => 18, 'nombremunicipio' => "SAN BUENAVENTURA"],
            ['codigodepto' => 8, 'codigomunicipio' => 19, 'nombremunicipio' => "SAN IGNACIO"],
            ['codigodepto' => 8, 'codigomunicipio' => 20, 'nombremunicipio' => "CANTARRANAS"],
            ['codigodepto' => 8, 'codigomunicipio' => 21, 'nombremunicipio' => "SAN MIGUELITO"],
            ['codigodepto' => 8, 'codigomunicipio' => 22, 'nombremunicipio' => "SANTA ANA"],
            ['codigodepto' => 8, 'codigomunicipio' => 23, 'nombremunicipio' => "SANTA LUCIA"],
            ['codigodepto' => 8, 'codigomunicipio' => 24, 'nombremunicipio' => "TALANGA"],
            ['codigodepto' => 8, 'codigomunicipio' => 25, 'nombremunicipio' => "TATUMBLA"],
            ['codigodepto' => 8, 'codigomunicipio' => 26, 'nombremunicipio' => "VALLE DE ANGELES"],
            ['codigodepto' => 8, 'codigomunicipio' => 27, 'nombremunicipio' => "VILLA SAN FRANCISCO"],
            ['codigodepto' => 8, 'codigomunicipio' => 28, 'nombremunicipio' => "VALLECILLOS"],
            ['codigodepto' => 9, 'codigomunicipio' => 1, 'nombremunicipio' => "PUERTO LEMPIRA"],
            ['codigodepto' => 9, 'codigomunicipio' => 2, 'nombremunicipio' => "BRUS LAGUNA"],
            ['codigodepto' => 9, 'codigomunicipio' => 3, 'nombremunicipio' => "AHUAS"],
            ['codigodepto' => 9, 'codigomunicipio' => 4, 'nombremunicipio' => "JUAN FRANCISCO BULNES"],
            ['codigodepto' => 9, 'codigomunicipio' => 5, 'nombremunicipio' => "VILLEDA MORALES"],
            ['codigodepto' => 9, 'codigomunicipio' => 6, 'nombremunicipio' => "WAMPUSIRPI"],
            ['codigodepto' => 10, 'codigomunicipio'=> 1, 'nombremunicipio' => "LA ESPERANZA"],
            ['codigodepto' => 10, 'codigomunicipio' => 2, 'nombremunicipio' => "CAMASCA"],
            ['codigodepto' => 10, 'codigomunicipio' => 3, 'nombremunicipio' => "COLOMONCAGUA"],
            ['codigodepto' => 10, 'codigomunicipio' => 4, 'nombremunicipio' => "CONCEPCION"],
            ['codigodepto' => 10, 'codigomunicipio' => 5, 'nombremunicipio' => "DOLORES"],
            ['codigodepto' => 10, 'codigomunicipio' => 6, 'nombremunicipio' => "INTIBUCA"],
            ['codigodepto' => 10, 'codigomunicipio' => 7, 'nombremunicipio' => "JESUS DE OTORO"],
            ['codigodepto' => 10, 'codigomunicipio' => 8, 'nombremunicipio' => "MAGDALENA"],
            ['codigodepto' => 10, 'codigomunicipio' => 9, 'nombremunicipio' => "MASAGUARA"],
            ['codigodepto' => 10, 'codigomunicipio' => 10, 'nombremunicipio' => "SAN ANTONIO"],
            ['codigodepto' => 10, 'codigomunicipio' => 11, 'nombremunicipio' => "SAN ISIDRO"],
            ['codigodepto' => 10, 'codigomunicipio' => 12, 'nombremunicipio' => "SAN JUAN"],
            ['codigodepto' => 10, 'codigomunicipio' => 13, 'nombremunicipio' => "SAN MARCOS SIERRA"],
            ['codigodepto' => 10, 'codigomunicipio' => 14, 'nombremunicipio' => "SAN MIGUELITO"],
            ['codigodepto' => 10, 'codigomunicipio' => 15, 'nombremunicipio' => "SANTA LUCIA"],
            ['codigodepto' => 10, 'codigomunicipio' => 16, 'nombremunicipio' => "YAMARANGUILA"],
            ['codigodepto' => 10, 'codigomunicipio' => 17, 'nombremunicipio' => "SAN FRANCISCO DE OPALACA"],
            ['codigodepto' => 11, 'codigomunicipio' => 1, 'nombremunicipio' => "ROATAN"],
            ['codigodepto' => 11, 'codigomunicipio' => 2, 'nombremunicipio' => "GUANAJA"],
            ['codigodepto' => 11, 'codigomunicipio' => 3, 'nombremunicipio' => "JOSE SANTOS GUARDIOLA"],
            ['codigodepto' => 11, 'codigomunicipio' => 4, 'nombremunicipio' => "UTILA"],
            ['codigodepto' => 12, 'codigomunicipio' => 1, 'nombremunicipio' => "LA PAZ"],
            ['codigodepto' => 12, 'codigomunicipio' => 2, 'nombremunicipio' => "AGUANQUETERIQUE"],
            ['codigodepto' => 12, 'codigomunicipio' => 3, 'nombremunicipio' => "CABAÑAS"],
            ['codigodepto' => 12, 'codigomunicipio' => 4, 'nombremunicipio' => "CANE"],
            ['codigodepto' => 12, 'codigomunicipio' => 5, 'nombremunicipio' => "CHINACLA"],
            ['codigodepto' => 12, 'codigomunicipio' => 6, 'nombremunicipio' => "GUAJIQUIRO"],
            ['codigodepto' => 12, 'codigomunicipio' => 7, 'nombremunicipio' => "LAUTERIQUE"],
            ['codigodepto' => 12, 'codigomunicipio' => 8, 'nombremunicipio' => "MARCALA"],
            ['codigodepto' => 12, 'codigomunicipio' => 9, 'nombremunicipio' => "MERCEDES DE ORIENTE"],
            ['codigodepto' => 12, 'codigomunicipio' => 10, 'nombremunicipio' => "OPATORO"],
            ['codigodepto' => 12, 'codigomunicipio' => 11, 'nombremunicipio' => "SAN ANTONIO DEL NORTE"],
            ['codigodepto' => 12, 'codigomunicipio' => 12, 'nombremunicipio' => "SAN JOSE"],
            ['codigodepto' => 12, 'codigomunicipio' => 13, 'nombremunicipio' => "SAN JUAN"],
            ['codigodepto' => 12, 'codigomunicipio' => 14, 'nombremunicipio' => "SAN PEDRO DE TUTULE"],
            ['codigodepto' => 12, 'codigomunicipio' => 15, 'nombremunicipio' => "SANTA ANA"],
            ['codigodepto' => 12, 'codigomunicipio' => 16, 'nombremunicipio' => "SANTA ELENA"],
            ['codigodepto' => 12, 'codigomunicipio' => 17, 'nombremunicipio' => "SANTA MARIA"],
            ['codigodepto' => 12, 'codigomunicipio' => 18, 'nombremunicipio' => "SANTIAGO DE PURINGLA"],
            ['codigodepto' => 12, 'codigomunicipio' => 19, 'nombremunicipio' => "YARULA"],
            ['codigodepto' => 13, 'codigomunicipio' => 1, 'nombremunicipio' => "GRACIAS"],
            ['codigodepto' => 13, 'codigomunicipio' => 2, 'nombremunicipio' => "BELEN"],
            ['codigodepto' => 13, 'codigomunicipio' => 3, 'nombremunicipio' => "CANDELARIA"],
            ['codigodepto' => 13, 'codigomunicipio' => 4, 'nombremunicipio' => "COLOLACA"],
            ['codigodepto' => 13, 'codigomunicipio' => 5, 'nombremunicipio' => "ERANDIQUE"],
            ['codigodepto' => 13, 'codigomunicipio' => 6, 'nombremunicipio' => "GUALCINCE"],
            ['codigodepto' => 13, 'codigomunicipio' => 7, 'nombremunicipio' => "GUARITA"],
            ['codigodepto' => 13, 'codigomunicipio' => 8, 'nombremunicipio' => "LA CAMPA"],
            ['codigodepto' => 13, 'codigomunicipio' => 9, 'nombremunicipio' => "LA IGUALA"],
            ['codigodepto' => 13, 'codigomunicipio' => 10, 'nombremunicipio' => "LAS FLORES"],
            ['codigodepto' => 13, 'codigomunicipio' => 11, 'nombremunicipio' => "LA UNION"],
            ['codigodepto' => 13, 'codigomunicipio' => 12, 'nombremunicipio' => "LA VIRTUD"],
            ['codigodepto' => 13, 'codigomunicipio' => 13, 'nombremunicipio' => "LEPAERA"],
            ['codigodepto' => 13, 'codigomunicipio' => 14, 'nombremunicipio' => "MAPULACA"],
            ['codigodepto' => 13, 'codigomunicipio' => 15, 'nombremunicipio' => "PIRAERA"],
            ['codigodepto' => 13, 'codigomunicipio' => 16, 'nombremunicipio' => "SAN ANDRES"],
            ['codigodepto' => 13, 'codigomunicipio' => 17, 'nombremunicipio' => "SAN FRANCISCO"],
            ['codigodepto' => 13, 'codigomunicipio' => 18, 'nombremunicipio' => "SAN JUAN GUARITA"],
            ['codigodepto' => 13, 'codigomunicipio' => 19, 'nombremunicipio' => "SAN MANUEL COLOHETE"],
            ['codigodepto' => 13, 'codigomunicipio' => 20, 'nombremunicipio' => "SAN RAFAEL"],
            ['codigodepto' => 13, 'codigomunicipio' => 21, 'nombremunicipio' => "SAN SEBASTIAN"],
            ['codigodepto' => 13, 'codigomunicipio' => 22, 'nombremunicipio' => "SANTA CRUZ"],
            ['codigodepto' => 13, 'codigomunicipio' => 23, 'nombremunicipio' => "TALGUA"],
            ['codigodepto' => 13, 'codigomunicipio' => 24, 'nombremunicipio' => "TAMBLA"],
            ['codigodepto' => 13, 'codigomunicipio' => 25, 'nombremunicipio' => "TOMALA"],
            ['codigodepto' => 13, 'codigomunicipio' => 26, 'nombremunicipio' => "VALLADOLID"],
            ['codigodepto' => 13, 'codigomunicipio' => 27, 'nombremunicipio' => "VIRGINIA"],
            ['codigodepto' => 13, 'codigomunicipio' => 28, 'nombremunicipio' => "SAN MARCOS DE CAIQUIN"],
            ['codigodepto' => 14, 'codigomunicipio' => 1, 'nombremunicipio' => "OCOTEPEQUE"],
            ['codigodepto' => 14, 'codigomunicipio' => 2, 'nombremunicipio' => "BELEN GUALCHO"],
            ['codigodepto' => 14, 'codigomunicipio' => 3, 'nombremunicipio' => "CONCEPCION"],
            ['codigodepto' => 14, 'codigomunicipio' => 4, 'nombremunicipio' => "DOLORES MERENDON"],
            ['codigodepto' => 14, 'codigomunicipio' => 5, 'nombremunicipio' => "FRATERNIDAD"],
            ['codigodepto' => 14, 'codigomunicipio' => 6, 'nombremunicipio' => "LA ENCARNACION"],
            ['codigodepto' => 14, 'codigomunicipio' => 7, 'nombremunicipio' => "LA LABOR"],
            ['codigodepto' => 14, 'codigomunicipio' => 8, 'nombremunicipio' => "LUCERNA"],
            ['codigodepto' => 14, 'codigomunicipio' => 9, 'nombremunicipio' => "MERCEDES"],
            ['codigodepto' => 14, 'codigomunicipio' => 10, 'nombremunicipio' => "SAN FERNANDO"],
            ['codigodepto' => 14, 'codigomunicipio' => 11, 'nombremunicipio' => "SAN FRANCISCO DEL VALLE"],
            ['codigodepto' => 14, 'codigomunicipio' => 12, 'nombremunicipio' => "SAN JORGE"],
            ['codigodepto' => 14, 'codigomunicipio' => 13, 'nombremunicipio' => "SAN MARCOS"],
            ['codigodepto' => 14, 'codigomunicipio' => 14, 'nombremunicipio' => "SANTA FE"],
            ['codigodepto' => 14, 'codigomunicipio' => 15, 'nombremunicipio' => "SENSENTI"],
            ['codigodepto' => 14, 'codigomunicipio' => 16, 'nombremunicipio' => "SINUAPA"],
            ['codigodepto' => 15, 'codigomunicipio' => 1, 'nombremunicipio' => "JUTICALPA"],
            ['codigodepto' => 15, 'codigomunicipio' => 2, 'nombremunicipio' => "CAMPAMENTO"],
            ['codigodepto' => 15, 'codigomunicipio' => 3, 'nombremunicipio' => "CATACAMAS"],
            ['codigodepto' => 15, 'codigomunicipio' => 4, 'nombremunicipio' => "CONCORDANCIA"],
            ['codigodepto' => 15, 'codigomunicipio' => 5, 'nombremunicipio' => "DULCE NOMBRE DE CULMI"],
            ['codigodepto' => 15, 'codigomunicipio' => 6, 'nombremunicipio' => "EL ROSARIO"],
            ['codigodepto' => 15, 'codigomunicipio' => 7, 'nombremunicipio' => "ESQUIPULAS DEL NORTE"],
            ['codigodepto' => 15, 'codigomunicipio' => 8, 'nombremunicipio' => "GUALACO"],
            ['codigodepto' => 15, 'codigomunicipio' => 9, 'nombremunicipio' => "GUARIZAMA"],
            ['codigodepto' => 15, 'codigomunicipio' => 10, 'nombremunicipio' => "GUATA"],
            ['codigodepto' => 15, 'codigomunicipio' => 11, 'nombremunicipio' => "GUAYAPE"],
            ['codigodepto' => 15, 'codigomunicipio' => 12, 'nombremunicipio' => "JANO"],
            ['codigodepto' => 15, 'codigomunicipio' => 13, 'nombremunicipio' => "LA UNION"],
            ['codigodepto' => 15, 'codigomunicipio' => 14, 'nombremunicipio' => "MANGULILE"],
            ['codigodepto' => 15, 'codigomunicipio' => 15, 'nombremunicipio' => "MANTO"],
            ['codigodepto' => 15, 'codigomunicipio' => 16, 'nombremunicipio' => "SALAMA"],
            ['codigodepto' => 15, 'codigomunicipio' => 17, 'nombremunicipio' => "SAN ESTEBAN"],
            ['codigodepto' => 15, 'codigomunicipio' => 18, 'nombremunicipio' => "SAN FRANCISCO DE BECERRA"],
            ['codigodepto' => 15, 'codigomunicipio' => 19, 'nombremunicipio' => "SAN FRANCISCO DE LA PAZ"],
            ['codigodepto' => 15, 'codigomunicipio' => 20, 'nombremunicipio' => "SANTA MARIA DEL REAL"],
            ['codigodepto' => 15, 'codigomunicipio' => 21, 'nombremunicipio' => "SILCA"],
            ['codigodepto' => 15, 'codigomunicipio' => 22, 'nombremunicipio' => "YOCON"],
            ['codigodepto' => 15, 'codigomunicipio' => 21, 'nombremunicipio' => "PATUCA"],
            ['codigodepto' => 16, 'codigomunicipio' => 1, 'nombremunicipio' => "SANTA BARBARA"],
            ['codigodepto' => 16, 'codigomunicipio' => 2, 'nombremunicipio' => "ARADA"],
            ['codigodepto' => 16, 'codigomunicipio' => 3, 'nombremunicipio' => "ATIMA"],
            ['codigodepto' => 16, 'codigomunicipio' => 4, 'nombremunicipio' => "AZACUALPA"],
            ['codigodepto' => 16, 'codigomunicipio' => 5, 'nombremunicipio' => "CEGUACA"],
            ['codigodepto' => 16, 'codigomunicipio' => 6, 'nombremunicipio' => "SAN JOSE DE COLINAS"],
            ['codigodepto' => 16, 'codigomunicipio' => 7, 'nombremunicipio' => "CONCEPCION DEL NORTE"],
            ['codigodepto' => 16, 'codigomunicipio' => 8, 'nombremunicipio' => "CONCEPCION DEL SUR"],
            ['codigodepto' => 16, 'codigomunicipio' => 9, 'nombremunicipio' => "CHINDA"],
            ['codigodepto' => 16, 'codigomunicipio' => 10, 'nombremunicipio' => "EL NISPERO"],
            ['codigodepto' => 16, 'codigomunicipio' => 11, 'nombremunicipio' => "GUALALA"],
            ['codigodepto' => 16, 'codigomunicipio' => 12, 'nombremunicipio' => "ILAMA"],
            ['codigodepto' => 16, 'codigomunicipio' => 13, 'nombremunicipio' => "MACUELIZO"],
            ['codigodepto' => 16, 'codigomunicipio' => 14, 'nombremunicipio' => "NARANJITO"],
            ['codigodepto' => 16, 'codigomunicipio' => 15, 'nombremunicipio' => "NUEVO CELILAC"],
            ['codigodepto' => 16, 'codigomunicipio' => 16, 'nombremunicipio' => "PEOTA"],
            ['codigodepto' => 16, 'codigomunicipio' => 17, 'nombremunicipio' => "PROTECCION"],
            ['codigodepto' => 16, 'codigomunicipio' => 18, 'nombremunicipio' => "QUIMISTAN"],
            ['codigodepto' => 16, 'codigomunicipio' => 19, 'nombremunicipio' => "SAN FRANCISCO DE OJUERA"],
            ['codigodepto' => 16, 'codigomunicipio' => 20, 'nombremunicipio' => "SAN LUIS"],
            ['codigodepto' => 16, 'codigomunicipio' => 21, 'nombremunicipio' => "SAN MARCOS"],
            ['codigodepto' => 16, 'codigomunicipio' => 22, 'nombremunicipio' => "SAN NICOLAS"],
            ['codigodepto' => 16, 'codigomunicipio' => 23, 'nombremunicipio' => "SAN PEDRO DE ZACAPA"],
            ['codigodepto' => 16, 'codigomunicipio' => 24, 'nombremunicipio' => "SANTA RITA"],
            ['codigodepto' => 16, 'codigomunicipio' => 25, 'nombremunicipio' => "SAN VICENTE CENTENARIO"],
            ['codigodepto' => 16, 'codigomunicipio' => 26, 'nombremunicipio' => "TRINIDAD"],
            ['codigodepto' => 16, 'codigomunicipio' => 27, 'nombremunicipio' => "LAS VEGAS"],
            ['codigodepto' => 16, 'codigomunicipio' => 28, 'nombremunicipio' => "NUEVA FRONTERA"],
            ['codigodepto' => 17, 'codigomunicipio' => 1, 'nombremunicipio' => "NACAOME"],
            ['codigodepto' => 17, 'codigomunicipio' => 2, 'nombremunicipio' => "ALIANZA"],
            ['codigodepto' => 17, 'codigomunicipio' => 3, 'nombremunicipio' => "AMAPALA"],
            ['codigodepto' => 17, 'codigomunicipio' => 4, 'nombremunicipio' => "ARAMECINA"],
            ['codigodepto' => 17, 'codigomunicipio' => 5, 'nombremunicipio' => "CARIDAD"],
            ['codigodepto' => 17, 'codigomunicipio' => 6, 'nombremunicipio' => "GOASCORAN"],
            ['codigodepto' => 17, 'codigomunicipio' => 7, 'nombremunicipio' => "LANGUE"],
            ['codigodepto' => 17, 'codigomunicipio' => 8, 'nombremunicipio' => "SAN FRANCISCO DE CORAY"],
            ['codigodepto' => 17, 'codigomunicipio' => 9, 'nombremunicipio' => "SAN LORENZO"],
            ['codigodepto' => 18, 'codigomunicipio' => 1, 'nombremunicipio' => "YORO"],
            ['codigodepto' => 18, 'codigomunicipio' => 2, 'nombremunicipio' => "ARENAL"],
            ['codigodepto' => 18, 'codigomunicipio' => 3, 'nombremunicipio' => "EL NEGRITO"],
            ['codigodepto' => 18, 'codigomunicipio' => 4, 'nombremunicipio' => "EL PROGRESO"],
            ['codigodepto' => 18, 'codigomunicipio' => 5, 'nombremunicipio' => "JOCON"],
            ['codigodepto' => 18, 'codigomunicipio' => 6, 'nombremunicipio' => "MORAZAN"],
            ['codigodepto' => 18, 'codigomunicipio' => 7, 'nombremunicipio' => "OLANCHITO"],
            ['codigodepto' => 18, 'codigomunicipio' => 8, 'nombremunicipio' => "SANTA RITA"],
            ['codigodepto' => 18, 'codigomunicipio' => 9, 'nombremunicipio' => "SULACO"],
            ['codigodepto' => 18, 'codigomunicipio' => 10, 'nombremunicipio' => "VICTORIA"],
            ['codigodepto' => 18, 'codigomunicipio' => 11, 'nombremunicipio' => "YORITO"],

        ];

        foreach ($municipios as $municipio) {
            Municipio::firstOrCreate($municipio);
        }

    }
}
