<?php

return [
    // Akaunting\Setting\Provider::class,
    // Anhskohbo\NoCaptcha\NoCaptchaServiceProvider::class,
    // App\Providers\AppServiceProvider::class,
    // App\Providers\TelescopeServiceProvider::class,
    // Artesaos\SEOTools\Providers\SEOToolsServiceProvider::class,
    // Barryvdh\Debugbar\ServiceProvider::class,
    // Barryvdh\Snappy\ServiceProvider::class,
    // Lab404\Impersonate\ImpersonateServiceProvider::class,
    // \Chatify\ChatifyServiceProvider::class,
    // Scyllaly\HCaptcha\HCaptchaServiceProvider::class,
    // Spatie\Permission\PermissionServiceProvider::class,
    // Yajra\DataTables\DataTablesServiceProvider::class,
    Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        PragmaRX\Google2FALaravel\ServiceProvider::class,
        Lab404\Impersonate\ImpersonateServiceProvider::class,
        // Spatie\Html\HtmlServiceProvider::class,
        Paytm\JsCheckout\PaytmServiceProvider::class,

        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        App\Providers\TelescopeServiceProvider::class,
        App\Providers\UtilityFacadesServiceProvider::class,
        Yajra\DataTables\DataTablesServiceProvider::class,
        RachidLaasri\LaravelInstaller\Providers\LaravelInstallerServiceProvider::class,
        Artesaos\SEOTools\Providers\SEOToolsServiceProvider::class,
        Barryvdh\Debugbar\ServiceProvider::class,
        \Chatify\ChatifyServiceProvider::class
];
