<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Nnapren extends Model
{
    use HasFactory;
    protected $fillable = [
        'IdDeclaPreRegistroNNA',
        'FchDeclaPreRegistroNNA',
        'EstadoDeclaPreRegistroNNA',
        'FechaProcesaDeclaPreRegistroNNA',
        'OrigenDeclaracion',
        'DNI_Solicitante',
        'NombresSolicitante',
        'PriApeSolicitante',
        'SeApeSolicitante',
        'TipoRelaSolicitante',
        'ParentescoSolicitante',
        'DNI_NNA',
        'NombresNNA',
        'PriApeNNA',
        'SeApeNNA',
        'FechaNacNNA',
        'DNI_Madre',
        'NombresMadre',
        'PriApeMadre',
        'SeApeMadre',
        'IdCiudadDomicilioMadre',
        'NombreCiudadDomicilioMadre',
        'IdPaisDomicilioMadre',
        'NombrePaisDomicilioMadre',
        'IdEstadoDomicilioMadre',
        'NombreEstadoDomicilioMadre',
        'IdColDomicilioMadre',
        'NombreColDomicilioMadre',
        'DireccionReferenciaNNAMadre',
        'TelefonoMadre',
        'EmailMadre',
        'DNI_Padre',
        'NombresPadre',
        'PriApePadre',
        'SeApePadre',
        'IdCiudadDomicilioPadre',
        'NombreCiudadDomicilioPadre',
        'IdPaisDomicilioPadre',
        'NombrePaisDomicilioPadre',
        'IdEstadoDomicilioPadre',
        'NombreEstadoDomicilioPadre',
        'IdColDomicilioPadre',
        'NombreColDomicilioPadre',
        'DireccionReferenciaNNAPadre',
        'TelefonoPadre',
        'EmailPadre',
        'NNAViveConPadres',
        'IdCiudadDomicilioNNA',
        'NombreCiudadDomicilioNNA',
        'IdPaisDomicilioNNA',
        'NombrePaisDomicilioNNA',
        'IdEstadoDomicilioNNA',
        'NombreEstadoDomicilioNNA',
        'idcoldomicilionna',
        'NombreColDomicilioNNA',
        'DireccionReferenciaNNA',
        'EmailNNA',
        'IdGrupoEtnicoNNA',
        'NombreGrupoEtnicoNNA',
        'TieneDiscapacidadNNA',
        'MostrarDiscapacidadDNI',
        'NNADiscaFisicaMotora',
        'NNADiscaSensorialVisual',
        'NNADiscaSensorialAuditiva',
        'NNADiscaMentalPsiquica',
        'NNADiscaMentalIintelectual',
        'NNADiscaOtra',
        'DNI_PerAutorizadaEntrega',
        'NombresPerAutorizadaEntrega',
        'PriApePerAutorizadaEntrega',
        'SeApePerAutorizadaEntrega',
        'TipoRelaPerAutorizadaEntrega',
        'ParentescoPerAutorizadaEntrega',
        'Genero_NNA'
    ];
}
